### ISSUE TITLE
docker volumes

### ISSUE THREAD

**Issue by steveoh** [Microsoft/vs4mac-labs#7]
is it normal to have to add `/usr/local/share/dotnet/sdk` to my docker shares for a docker-compose file like so?

![image](https://user-images.githubusercontent.com/325813/41327808-1b3a2bae-6e82-11e8-9b98-e7bf84a1cc6c.png)

```yml
version: '3.6'

services:
  webapi-core:
    links:
      - postgres
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:1337
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1337:1337"
  postgres:
    environment:
      - POSTGRES_DB=webapi
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    external: true
```
